<a href="https://colab.research.google.com/github/febriandfa/preprocessing/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import Dependencies**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest, f_classif
from imblearn.over_sampling import SMOTE

**Collect Data**

In [ ]:
d_data = pd.read_csv('/content/diabetes.csv')
d_data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
d_data.shape

(768, 9)

In [ ]:
d_data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

**Duplicate Value**

In [ ]:
duplicate_rows = d_data.duplicated()
print(duplicate_rows)

0      False
1      False
2      False
3      False
4      False
       ...  
763    False
764    False
765    False
766    False
767    False
Length: 768, dtype: bool


**Missing Value**

In [ ]:
d_data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

**Split Feature and Target**

In [ ]:
X = d_data.drop(columns="Outcome", axis=1)
Y = d_data["Outcome"]

In [ ]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  


In [ ]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


**Selection Feature**

In [ ]:
num_features_to_select = 5
feature_selector = SelectKBest(score_func=f_classif, k=num_features_to_select)
X_selected = feature_selector.fit_transform(X, Y)

In [ ]:
selected_features = feature_selector.get_support(indices=True)
print("Fitur yang dipilih:", d_data.columns[selected_features])

Fitur yang dipilih: Index(['Pregnancies', 'Glucose', 'BMI', 'DiabetesPedigreeFunction', 'Age'], dtype='object')


**Standardization**

In [ ]:
scaler = StandardScaler()

In [ ]:
standard_data_X = scaler.fit_transform(X_selected)
standard_data_X.shape

(768, 5)

In [ ]:
print(standard_data_X)

[[ 0.63994726  0.84832379  0.20401277  0.46849198  1.4259954 ]
 [-0.84488505 -1.12339636 -0.68442195 -0.36506078 -0.19067191]
 [ 1.23388019  1.94372388 -1.10325546  0.60439732 -0.10558415]
 ...
 [ 0.3429808   0.00330087 -0.73518964 -0.68519336 -0.27575966]
 [-0.84488505  0.1597866  -0.24020459 -0.37110101  1.17073215]
 [-0.84488505 -0.8730192  -0.20212881 -0.47378505 -0.87137393]]


In [ ]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


**Reduction Data**

In [ ]:
num_components = 2
pca = PCA(n_components=num_components)
reduced_data_X = pca.fit_transform(standard_data_X)
reduced_data_X.shape

(768, 2)

In [ ]:
print(reduced_data_X)

[[ 1.76000992  0.11890344]
 [-1.30333188 -0.67517544]
 [ 1.35026236 -0.00503703]
 ...
 [-0.22528625 -0.87412458]
 [ 0.22619787 -0.26208976]
 [-1.53666949 -0.18998075]]


**Resampling Data**

In [ ]:
unique_target, target_count = np.unique(Y, return_counts=True)

In [ ]:
print(dict(zip(unique_target, target_count)))

{0: 500, 1: 268}


In [ ]:
smote = SMOTE(sampling_strategy='auto')
X_resampled, Y_resampled = smote.fit_resample(reduced_data_X, Y)

In [ ]:
unique_target, target_count = np.unique(Y_resampled, return_counts=True)

In [ ]:
print(dict(zip(unique_target, target_count)))

{0: 500, 1: 500}
